### ISSUE TITLE
Please tag current code base as 2.1.0?

### ISSUE THREAD

**Issue by gonzoleeman** [linux-ras/sysfsutils#1]
Hi! Thank you for setting up this repo! Long live FOSS. :)

Can you please tag the current code as "2.1.0"? This is the version tag I have on a tarball in the distro that I manage, and that tarball matches this repo's code, save for three "$Id$" strings, which I don't think matter.

So if you could tag the current code 2.1.0, then I can submit some patches. Some day we may even need a 2.1.1!

Thank you again.

**Comment by kamalesh-babulal** [comment]
Thank you for noticing the missing tags. I have pushed tags for all the releases. Patches are most welcome and thanks for the first PR :)
