### ISSUE TITLE
Build failure with GCC-11 due to stringop-overread

### ISSUE THREAD

**Issue by lcts** [linux-ras/sysfsutils#12]
[`sys_fs_class_device`](https://github.com/linux-ras/sysfsutils/blob/master/include/libsysfs.h#L108) in `libsysfs.h` defines `name` as a SYSFS_NAME_LEN-byte char:
```
struct sysfs_class_device {
	char name[SYSFS_NAME_LEN];
```
, but [`cdev_name_equal`](https://github.com/linux-ras/sysfsutils/blob/master/lib/sysfs_class.c#L78) tries to read SYSFS_NAME_LEN+1 bytes from it:
```
str_b = ((struct sysfs_class_device *)b)->name;

length_a = strnlen(str_a, SYSFS_NAME_LEN+1);
length_b = strnlen(str_b, SYSFS_NAME_LEN+1);
```
This will cause build failures with GCC-11.

Removing the +1 in line 81 fixes the issue (unless `name` is supposed to be SYSFS_NAME_LEN+1 bytes long?), but I don't think any of the +1s (in lines 80, 81 and 86) are actually needed:
- strlen of str_b is at most SYSFS_NAME_LEN-1, as name is only SYSFS_NAME_LEN bytes. Reading SYSFS_NAME_LEN bytes will always catch the NULL byte.
- strlen of str_a is at most SYSFS_NAME_LEN, but only if no NULL byte is encountered.
- thus, length_a and length_b can only be identical if the length_a+1 byte of both is NULL, so there's no need to compare those.

**Comment by kamalesh-babulal** [comment]
> Removing the +1 in line 81 fixes the issue (unless name is supposed to be SYSFS_NAME_LEN+1 bytes long?)

@lcts Thanks for testing it on `GCC-11`.  The `SYSFS_NAME_LEN` should be inclusive of the `NULL` byte and it needs to be fixed my bad of having this discussion during the review but merging it without integrating the LEN change to it.  

>  but I don't think any of the +1s (in lines 80, 81 and 86) are actually needed:
> strlen of str_b is at most SYSFS_NAME_LEN-1, as name is only SYSFS_NAME_LEN bytes. Reading SYSFS_NAME_LEN bytes will always catch the NULL byte.
> strlen of str_a is at most SYSFS_NAME_LEN, but only if no NULL byte is encountered.
> thus, length_a and length_b can only be identical if the length_a+1 byte of both is NULL, so there's no need to compare those.

are you suggesting something like:
```
--- a/lib/sysfs_class.c
+++ b/lib/sysfs_class.c
@@ -68,7 +68,6 @@ void sysfs_close_class(struct sysfs_class *cls)
  */
 static int cdev_name_equal(void *a, void *b)
 {
-       size_t length_a, length_b;
        char *str_a, *str_b;
 
        if (!a || !b)
@@ -77,13 +76,7 @@ static int cdev_name_equal(void *a, void *b)
        str_a = (char *)a;
        str_b = ((struct sysfs_class_device *)b)->name;
 
-       length_a = strnlen(str_a, SYSFS_NAME_LEN+1);
-       length_b = strnlen(str_b, SYSFS_NAME_LEN+1);
-
-       if (length_a != length_b)
-               return 0;
-
-       if (strncmp(str_a, str_b, length_a+1) == 0)
+       if (strncmp(str_a, str_b, SYSFS_NAME_LEN) == 0)
                return 1;
 
        return 0;
```

**Comment by lcts** [comment]
I was thinking about literally just removing the '+1' from the three strlen()/strncmp() calls, but your way is much cleaner.

The detour via length_a != length_b was introduced to protect against something like strncmp('eth0', 'eth10', strlen('eth0') returning zero, right? But reading SYSFS_NAME_LEN from str_b always includes the NULL byte, so in the original error case, strncmp() will at some point read NULL from str_b and something else from str_a.

**Comment by kamalesh-babulal** [comment]
> The detour via length_a != length_b was introduced to protect against something like strncmp('eth0', 'eth10', strlen('eth0') returning zero, right? 

Yes, thats right. It was the reason to introduce those checks.

> But reading SYSFS_NAME_LEN from str_b always includes the NULL byte, so in the original error case, strncmp() will at some point read NULL from str_b and something else from str_a.

from `glibc/string/strncmp.c`
```
...
  while (n > 0)
    {
      c1 = (unsigned char) *s1++;
      c2 = (unsigned char) *s2++;
      if (c1 == '\0' || c1 != c2)
        return c1 - c2;
      n--;
    }

  return c1 - c2;
```
considering the case where `str_a` is shorter than `str_b` it will return negative number the moment `\0` is encountered a.k.a. not equal and other case where `str_b` is shorter than `str_a`, will again return negative, when `\0` matches some other character in `str_a`.  I guess, it should work. I might be overlooking something here.

**Comment by lcts** [comment]
Yes, I think it's all good unless neither string contains `\0` due to truncation, which was the issue with the original code but should be impossible when n = SYSFS_NAME_LEN.

Edit: Tested [here](https://github.com/linux-ras/sysfsutils/compare/master...lcts:gcc-11-fixes) - as expected, this version causes no issues with GCC-11.

**Comment by kamalesh-babulal** [comment]
> Yes, I think it's all good unless neither string contains \0 due to truncation, which was the issue with the original code but should be impossible when n = SYSFS_NAME_LEN.

Thanks for testing it. True, then `SYSFS_NAME_LEN` needs to be increased to what the Linux kernel has increased them to. I will send a PR soon.
