### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [linux-ras/sysfsutils#20]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by kamalesh-babulal** [comment]
@kloczek Yes, that's the plan. Will make the release sooner :)

**Comment by kloczek** [comment]
👍

**Comment by kloczek** [comment]
Any progress? :P

**Comment by kamalesh-babulal** [comment]
@kloczek Sorry away for a couple of weeks. Happy new year. Yes, should be done in the week starting next month.

**Comment by kamalesh-babulal** [comment]
Task list to new release
- [ ] Changelog update - Assigned to Kamalesh (In progess)

**Comment by kamalesh-babulal** [comment]
@kloczek We have a new release 2.1.1 today. Thank you for your patience.

**Comment by kloczek** [comment]
Just updated my rpm package with sysfsutils.
So far everything is OK :)

Thank you.
